Upload Button/Progress Bar/Init bootloader process
daqifi/daqifi-desktop pull request #19
Opened 2023-03-22 21:34 UTC by josemapac2

+ Adding a progress bar close to the button "Upload" in the "Device Settings/Update Firmware" menu.
+ Making the "Upload" button work to Update the Firmware, by forcing the bootloader process sending a command through the USB serial port. 
+ Fix the bug in the view CONNECT DEVICE to automatically detect all Daqifi USB ports: Check there is no 'null'

2023-03-31 03:10 UTC, tylerkron requested changes
Thanks for the PR! Just a couple of cleanup items I saw!

2023-03-31 03:10 UTC, tylerkron commented on Daqifi.Desktop.Setup/UpgradeLog2.htm
> +﻿<!DOCTYPE html>
We don't need to check in this file

2023-03-31 03:10 UTC, tylerkron commented on Daqifi.Desktop.Setup/UpgradeLog.htm
> +﻿<!DOCTYPE html>
Don't need to check in this file

2023-03-31 03:10 UTC, tylerkron commented on Daqifi.Desktop/ViewModels/DaqifiViewModel.cs
> +        //private readonly Pic32Bootloader _bootloader;
Delete this commented line?

2023-03-31 03:10 UTC, tylerkron commented on Daqifi.Desktop/ViewModels/DaqifiViewModel.cs
> +using System.Diagnostics;
This is unused

2023-03-31 03:10 UTC, tylerkron commented on Daqifi.Desktop/ViewModels/DaqifiViewModel.cs
> +using System.Windows.Interop;
This is unused

2023-05-16 17:42 UTC, cptkoolbeenz approved these changes
Using firmware update feature with stock bootloader causes Windows confusion when switching from COM to HID device rapidly.  Adding a 2s delay during bootloader startup solves this issue.

2023-05-20 02:26 UTC, merged