feat: #44 Feature current session profile
daqifi/daqifi-desktop pull request #48
Opened 2024-09-24 15:18 UTC by codedecoded01723

1.Added multi device capabilities
2.Added current settings save option
3.Changes asked by tyler 
4.Added confirmation dialog
5.Added and implemented multi profile active 
6.Changed the  edit options for profile

2024-09-25 02:38 UTC, tylerkron requested changes
There are a handful of Codacy (static code analysis) issues. Please address those first, they should be pretty quick to fix. In the mean time I'll do some testing locally!

2024-09-27 04:13 UTC, tylerkron requested changes
Looking good! just a few comments

2024-09-27 04:13 UTC, tylerkron commented on Daqifi.Desktop/View/AddprofileDialog.xaml.cs
> +        }
Is `SelectedDevice_PreviewMouseDown` used anywhere? It doesn't seem to do anything

2024-09-27 04:13 UTC, tylerkron commented on Daqifi.Desktop/View/Flyouts/UpdateProfileFlyout.xaml.cs
> +        }
Does `UpdatedProfileChannelListSelectionChanged` do anything?

2024-09-27 04:13 UTC, tylerkron commented on Daqifi.Desktop/ViewModels/AddProfileDialogViewModel.cs
> +                //checkAddProfileButton();
Can this commented code be deleted?

2024-09-27 04:13 UTC, tylerkron commented on Daqifi.Desktop/ViewModels/AddProfileDialogViewModel.cs
> +               // checkAddProfileButton();
Can delete?

2024-09-27 08:51 UTC, codedecoded01723 commented on Daqifi.Desktop/ViewModels/AddProfileDialogViewModel.cs
> +                //checkAddProfileButton();
done , fixed.

2024-09-27 08:51 UTC, codedecoded01723 commented on Daqifi.Desktop/View/AddprofileDialog.xaml.cs
> +        }
done , fixed.

2024-09-30 22:47 UTC, tylerkron approved these changes

2024-10-01 02:37 UTC, tylerkron requested changes
I was doing some final testing. I deleted all my profiles (I deleted the profiles file too). After doing so, I wasn't able to create a new profile. 
![image](https://github.com/user-attachments/assets/3613cb0a-1a33-4ebd-9411-02c1542a8df7)

2024-10-05 02:46 UTC, tylerkron requested changes
We are very close on this. Please prioritize getting this feature working before continuing with other features.

## Issue: Only 1 channel actually gets logged
When testing, there is a problem. I selected 5 analog channels. It looks like 5 are selected when I apply the profile. However, when I run the logging, only the first channel is actually logged.

Reproduction Steps
1. Create a new profile
2. Select channels AI0, AI1, AI2, AI3, AI4
3. Active the profile
4. Go the live graph
5. Turn logging on. Notice you only see one channel actually being logged
6. Stop logging
7. Find the session in Logged Data and verify that only one channel was logged
![image](https://github.com/user-attachments/assets/937db307-5972-417b-84e3-5b1204cc380c)


## Issue - Cant' set 1Hz as a frequency
When creating a profile, I can't set the frequency to 1Hz. 2Hz seems to be the minimum but 1Hz is valid
![image](https://github.com/user-attachments/assets/778130c3-d8ea-43e1-8b89-d8e6901f8a5d)
![image](https://github.com/user-attachments/assets/dd074244-6273-4652-b431-e874ce172f91)


## Issue - Multiple Active Profiles
I should only be able to set one active at a time.
![image](https://github.com/user-attachments/assets/2b896776-9322-4ffd-84be-0577d413017d)

2024-10-09 14:54 UTC, closed without merging