feat: Initial Probuf changes Proto2 to Proto3
daqifi/daqifi-desktop pull request #61
Opened 2024-10-24 15:28 UTC by codedecoded01723

2024-11-05 05:05 UTC, tylerkron requested changes
This doesn't look like it includes the new dependency

2024-11-05 05:32 UTC, tylerkron requested changes
Found some primitives that can't be null. We'll need to change those checks.

2024-11-05 05:32 UTC, tylerkron commented on Daqifi.Desktop/Device/AbstractStreamingDevice.cs
> +            if (message.MsgTimeStamp != null)
MsgTimeStamp is a `uint` which is a primitive type and thus can't be null.

I'd change this to `if (message.MsgTimeStamp == 0)`

2024-11-05 05:32 UTC, tylerkron commented on Daqifi.Desktop/Device/AbstractStreamingDevice.cs
> +            if (message.AnalogInPortNum ==null) return;
Same here. This can never be null since it's a `unit`

2024-11-05 05:32 UTC, tylerkron commented on Daqifi.Desktop/Device/AbstractStreamingDevice.cs
> +            if (message.WifiSecurityMode !=null)
Can't be null

2024-11-05 05:32 UTC, tylerkron commented on Daqifi.Desktop/Device/AbstractStreamingDevice.cs
> +            if (message.WifiInfMode !=null)
Can't be null

2024-11-05 05:32 UTC, tylerkron commented on Daqifi.Desktop/Device/AbstractStreamingDevice.cs
> +            if (message.DeviceSn !=null)
Can't be null

2024-11-05 05:32 UTC, tylerkron commented on Daqifi.Desktop/Device/AbstractStreamingDevice.cs
> +            if (message.DigitalPortNum == null) return;
Can't be null

2024-11-05 05:32 UTC, tylerkron commented on Daqifi.Desktop/Device/AbstractStreamingDevice.cs
> +            if (message.AnalogOutPortNum == null) return;
Can't be null

2024-11-05 07:34 UTC, codedecoded01723 commented
> This doesn't look like it includes the new dependency

Hi can you give more insight , what do mean here ?

2024-11-06 04:50 UTC, tylerkron commented
> > This doesn't look like it includes the new dependency
> 
> Hi can you give more insight , what do mean here ?

I mean checked out this branch and it still had the old protobuf library instead of the new one. I would expect there would be change with a `.csproj` file

2024-11-08 04:47 UTC, tylerkron approved these changes

2024-11-26 06:08 UTC, merged